# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 130f583ac751b3dc45b3fe7599fc484d4c90f29fe7201bfa3d742df1d9fb568da8873ceb8086ede7bf439d2fcc9cec024528bb3fec0c24fa4c9c4cc338e9518c

test:
  secret_key_base: 86f6a33b0b1b939d43aab1ebcdce775d0d1cf8d3f7da7597c53a70d75401d71a74aaa3422028b7e58ab47e2ee643214dff06412d41454ae0c45685fcd1e1f425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
